language: node_js
node_js: stable

script:
  - cd  ./www
  - git init
  - git config user.name "poetries"
  - git config user.email "jingguanliuye@gmail.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/poetries/ionic-qa-app.git


